version: "3.9"

services:
    web1:
        build: ./StormBroker
        volumes:
            - jobs:/jobs
            - results:/results
            - /etc/letsencrypt/live/${TARGET_URL}/fullchain.pem:/etc/fullchain.pem
            - /etc/letsencrypt/live/${TARGET_URL}/privkey.pem:/etc/privkey.pem
        command: pm2-runtime start http-server -- --port 443 -S -C /etc/fullchain.pem -K /etc/privkey.pem --proxy https://${TARGET_URL}
        ports:
            - 443:443
    web2:
        build: ./StormBroker
        volumes:
            - jobs:/jobs
            - results:/results
        command: pm2-runtime start http-server -- --port 80 --proxy https://${TARGET_URL}
        ports:
            - 80:80
volumes:
    jobs:
    results: