version: "3.9"

services:
    web:
        build: ./StormBroker
        command: pm2-runtime start http-server -- -a 0.0.0.0
        expose:
            - 8080
        networks:
            - backbone
    nginx:
        build: ./nginx
        networks:
            - backbone
        ports:
            - 80:80
            - 443:443
        volumes:
            - /etc/letsencrypt/live/stormbroker.dclimate.net/fullchain.pem:/etc/fullchain.pem
            - /etc/letsencrypt/live/stormbroker.dclimate.net/privkey.pem:/etc/privkey.pem

networks:
  backbone:
    driver: bridge