version: "3.9"

services:
    web:
        build: ./StormBroker
        network_mode: host
        command: http-server
        volumes:
            - jobs:/jobs
            - results:/results
        expose:
            - 8080
    
    nginx:
        build: ./nginx
        ports:
            - 80:80
        depends_on:
            - web
        volumes:
            - jobs:/jobs
            - results:/results

volumes:
  jobs:
  results: